In [2]:
import torch
import numpy as np

In [67]:
x = torch.tensor([0.8, 0.1, 0.1])
y = torch.tensor([0.5, 0.3, 0.2])

p = x.unsqueeze(0) * y.unsqueeze(1)
I = -p * p.log()
pt = (p + p.t()/2)
It = -pt * pt.log()

print('p', p.sum())
print('pt', pt.sum())
print('I', I.sum())
print('It', It.sum())
print()

x = torch.tensor([0.8, 0.1, 0.1])
y = torch.tensor([0.7, 0.2, 0.1])

p = x.unsqueeze(0) * y.unsqueeze(1)
I = -p * p.log()
pt = (p + p.t()/2)
It = -pt * pt.log()

print('p', p.sum())
print('pt', pt.sum())
print('I', I.sum())
print('It', It.sum())
print()

x = torch.tensor([0.8, 0.1, 0.1])
y = torch.tensor([0.8, 0.1, 0.1])

p = x.unsqueeze(0) * y.unsqueeze(1)
I = -p * p.log()
pt = (p + p.t()/2)
It = -pt * pt.log()

print('p', p.sum())
print('pt', pt.sum())
print('I', I.sum())
print('It', It.sum())
print()


x = torch.tensor([0.5, 0.4, 0.1])
y = torch.tensor([0.5, 0.4, 0.1])

p = x.unsqueeze(0) * y.unsqueeze(1)
I = -p * p.log()
pt = (p + p.t()/2)
It = -pt * pt.log()

print('p', p.sum())
print('pt', pt.sum())
print('I', I.sum())
print('It', It.sum())
print()



p tensor(1.0000)
pt tensor(1.5000)
I tensor(1.6687)
It tensor(2.0279)

p tensor(1.0000)
pt tensor(1.5000)
I tensor(1.4409)
It tensor(1.5800)

p tensor(1.0000)
pt tensor(1.5000)
I tensor(1.2781)
It tensor(1.3089)

p tensor(1.)
pt tensor(1.5000)
I tensor(1.8867)
It tensor(2.2218)



In [42]:
x = torch.tensor([
    [0.1, 0.1, 0.8],
    [0.8, 0.1, 0.1],
])

y1 = torch.tensor([
    [0.1, 0.1, 0.8],
    [0.5, 0.3, 0.2],
])

y2 = torch.tensor([
    [0.1, 0.1, 0.8],
    [0.7, 0.2, 0.1],
])

In [43]:
# h1 = x * y1.log() + x.log() * y1
# print(h1)
# print(h1.sum(dim=1))
# print(h1.shape)

# h2 = x*y2.log() + x.log()*y2
# print(h2)
# print(h2.sum(dim=1))
# print(h2.shape)

p = x.unsqueeze(2) * y1.unsqueeze(1)
print(p)
p = p.sum(dim=0)
print(p)

p_i = p.sum(0)
print('Pi', p_i)

p_j = p.sum(1)
print('Pj', p_j)

print('mul', (x*y1).sum(0))
print('cross', (- x*y1.log() - x.log()*y1))
print('cross', (- x*y1.log() - x.log()*y1).sum())

tensor([[[0.0100, 0.0100, 0.0800],
         [0.0100, 0.0100, 0.0800],
         [0.0800, 0.0800, 0.6400]],

        [[0.4000, 0.2400, 0.1600],
         [0.0500, 0.0300, 0.0200],
         [0.0500, 0.0300, 0.0200]]])
tensor([[0.4100, 0.2500, 0.2400],
        [0.0600, 0.0400, 0.1000],
        [0.1300, 0.1100, 0.6600]])
Pi tensor([0.6000, 0.4000, 1.0000])
Pj tensor([0.9000, 0.2000, 0.9000])
mul tensor([0.4100, 0.0400, 0.6600])
cross tensor([[0.4605, 0.4605, 0.3570],
        [0.6661, 0.8112, 0.6215]])
cross tensor(3.3768)


In [41]:
p = x.unsqueeze(2) * y2.unsqueeze(1)
print(p)
p = p.sum(dim=0)
print(p)

p_i = p.sum(0)
print('Pi', p_i)

p_j = p.sum(1)
print('Pj', p_j)

print('mul', (x*y2).sum(0))
print('cross', (- x*y2.log() - x.log()*y2))
print('cross', (- x*y2.log() - x.log()*y2).sum())

tensor([[[0.0100, 0.0100, 0.0800],
         [0.0100, 0.0100, 0.0800],
         [0.0800, 0.0800, 0.6400]],

        [[0.5600, 0.1600, 0.0800],
         [0.0700, 0.0200, 0.0100],
         [0.0700, 0.0200, 0.0100]]])
tensor([[0.5700, 0.1700, 0.1600],
        [0.0800, 0.0300, 0.0900],
        [0.1500, 0.1000, 0.6500]])
Pi tensor([0.8000, 0.3000, 0.9000])
Pj tensor([0.9000, 0.2000, 0.9000])
mul tensor([0.5700, 0.0300, 0.6500])
cross tensor([[0.4605, 0.4605, 0.3570],
        [0.4415, 0.6215, 0.4605]])
cross tensor(2.8016)
