In [1]:
import torch
import numpy as np

In [2]:
x = torch.tensor([
    [0.8, 0.1, 0.1],
    [0.7, 0.2, 0.1],
    [0.1, 0.5, 0.4],
    [0.1, 0.7, 0.2],    
])

print('エントロピーの平均: 尖っていてほしい→小さくなってほしい')
Hx = -torch.log(x)*x
print(Hx.mean(axis=0))
print(Hx.mean(axis=0).sum())


print('平均のエントロピー: データ間では散らばっていてほしい→大きくなってほしい')
x2 = x.mean(axis=0)
Hx2 = -torch.log(x2)*x2
print(Hx2)
print(Hx2.sum())

エントロピーの平均: 尖っていてほしい→小さくなってほしい
tensor([0.2222, 0.2871, 0.2872])
tensor(0.7965)
平均のエントロピー: データ間では散らばっていてほしい→大きくなってほしい
tensor([0.3637, 0.3678, 0.3219])
tensor(1.0534)


In [3]:
print('各データの尖りが増すケース')

x = torch.tensor([
    [0.8, 0.1, 0.1],
    [0.7, 0.2, 0.1],
    [0.1, 0.9, 0.4],
    [0.1, 0.8, 0.1],     
])

print('エントロピーの平均: 尖っていてほしい→小さくなってほしい')
Hx = -torch.log(x)*x
print(Hx.mean(axis=0))
print(Hx.mean(axis=0).sum())


print('平均のエントロピー: データ間では散らばっていてほしい→大きくなってほしい')
x2 = x.mean(axis=0)
Hx2 = -torch.log(x2)*x2
print(Hx2)
print(Hx2.sum())

各データの尖りが増すケース
エントロピーの平均: 尖っていてほしい→小さくなってほしい
tensor([0.2222, 0.2064, 0.2643])
tensor(0.6929)
平均のエントロピー: データ間では散らばっていてほしい→大きくなってほしい
tensor([0.3637, 0.3466, 0.3050])
tensor(1.0153)


In [4]:
print('各データの散らばりが増える')

x = torch.tensor([
    [0.8, 0.1, 0.1],
    [0.1, 0.2, 0.7],
    [0.1, 0.5, 0.4],
    [0.1, 0.7, 0.2],    
])

print('エントロピーの平均: 尖っていてほしい→小さくなってほしい')
Hx = -torch.log(x)*x
print(Hx.mean(axis=0))
print(Hx.mean(axis=0).sum())


print('平均のエントロピー: データ間では散らばっていてほしい→大きくなってほしい')
x2 = x.mean(axis=0)
Hx2 = -torch.log(x2)*x2
print(Hx2)
print(Hx2.sum())

各データの散らばりが増える
エントロピーの平均: 尖っていてほしい→小さくなってほしい
tensor([0.2173, 0.2871, 0.2921])
tensor(0.7965)
平均のエントロピー: データ間では散らばっていてほしい→大きくなってほしい
tensor([0.3550, 0.3678, 0.3674])
tensor(1.0903)
